name: "MongoDB in GitHub Actions"
description: "Start a MongoDB server (on default port 27017 or a custom port)"

branding:
  icon: "database"
  color: "green"

inputs:
  mongodb-version:
    description: 'MongoDB version to use (default "latest")'
    required: false
    default: "latest"

  mongodb-replica-set:
    description: "MongoDB replica set name (no replica set by default)"
    required: false
    default: ""

  mongodb-port:
    description: "MongoDB port to use (default 27017)"
    required: false
    default: 27017

  mongodb-db:
    description: "MongoDB db to create (default: none)"
    required: false
    default: ""

  mongodb-username:
    description: "MongoDB root username (default: none)"
    required: false
    default: ""

  mongodb-password:
    description: "MongoDB root password (default: none)"
    required: false
    default: ""

  folderone:
    description: "Mount folder one"
    required: false

  foldertwo:
    description: "Mount folder two"
    required: false

  work-dir:
    description: "Current work-dir"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Delete Old Themes
      env:
        MONGODB_VERSION: ${{ inputs.mongodb-version }}
        MONGODB_REPLICA_SET: ${{ inputs.mongodb-replica-set }}
        MONGODB_PORT: ${{ inputs.mongodb-port }}
        MONGODB_DB: ${{ inputs.mongodb-db }}
        MONGODB_USERNAME: ${{ inputs.mongodb-username }}
        MONGODB_PASSWORD: ${{ inputs.mongodb-password }}
        FOLDER_ONE: ${{ inputs.folderone }}
        FOLDER_TWO: ${{ inputs.foldertwo }}
        WORK_DIR: ${{ inputs.work-dir }}
      run: ${{ github.action_path }}/start-mongodb.sh
      shell: bash

# runs:
#   using: "docker"
#   image: "Dockerfile"
#   args:
#     - ${{ inputs.mongodb-version }}
#     - ${{ inputs.mongodb-replica-set }}
#     - ${{ inputs.mongodb-port }}
#     - ${{ inputs.mongodb-db }}
#     - ${{ inputs.mongodb-username }}
#     - ${{ inputs.mongodb-password }}
#     - ${{ inputs.folderone }}
#     - ${{ inputs.foldertwo }}
#     - ${{ inputs.work-dir }}
